######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 8 23:02:46 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include src
INCLUDEPATH += . include

# Input
HEADERS += include/mainwindow.h
SOURCES += src/main.cpp src/mainwindow.cpp
